//
//  TestList.swift
//  hms-structured
//
//  Created by srijan mishra on 30/04/24.
//

//
//  TestsList.swift
//  hms
//
//  Created by srijan mishra on 24/04/24.
//

import SwiftUI


let testList: [Test] = [
    Test(name: "Blood Test"),
    Test(name: "X-Ray"),
    Test(name: "MRI"),
    Test(name: "CT Scan"),
    Test(name: "Ultrasound"),
    Test(name: "ECG (Electrocardiogram)"),
    Test(name: "EEG (Electroencephalogram)"),
    Test(name: "Treadmill Test (TMT)"),
    Test(name: "Echocardiogram"),
    Test(name: "Pulmonary Function Test (PFT)"),
    Test(name: "Endoscopy"),
    Test(name: "Colonoscopy"),
    Test(name: "Biopsy"),
    Test(name: "Bone Density Test (DXA Scan)"),
    Test(name: "Thyroid Function Test"),
    Test(name: "Liver Function Test"),
    Test(name: "Kidney Function Test"),
    Test(name: "Lipid Profile Test"),
    Test(name: "Blood Sugar Test"),
    Test(name: "HIV Test"),
    Test(name: "Hepatitis Panel"),
    Test(name: "Pap Smear Test"),
    Test(name: "Mammogram"),
    Test(name: "Prostate Specific Antigen (PSA) Test"),
    Test(name: "Thyroid Scan"),
    Test(name: "Cervical Cancer Screening"),
    Test(name: "Bone Marrow Test"),
    Test(name: "Arterial Blood Gas (ABG) Test"),
    Test(name: "Serum Creatinine Test"),
    Test(name: "Urine Culture Test"),
    Test(name: "Stool Culture Test"),
    Test(name: "Electromyography (EMG)"),
    Test(name: "Nerve Conduction Study (NCS)"),
    Test(name: "Cardiac Stress Test"),
    Test(name: "Holter Monitor Test"),
    Test(name: "Skin Allergy Test"),
    Test(name: "Patch Test"),
    Test(name: "Sputum Culture Test"),
    Test(name: "Throat Culture Test"),
    Test(name: "Eye Examination"),
    Test(name: "Dental Examination"),
    Test(name: "Vitamin D Test"),
    Test(name: "Vitamin B12 Test"),
    Test(name: "C-reactive Protein (CRP) Test"),
    Test(name: "Rheumatoid Factor Test"),
    Test(name: "Autoimmune Antibody Tests"),
    Test(name: "Hemoglobin A1c Test"),
    Test(name: "Thrombophilia Test"),
    Test(name: "Antinuclear Antibody (ANA) Test"),
    Test(name: "Cortisol Test"),
    Test(name: "Thyroid Antibody Tests"),
    Test(name: "Glucose Tolerance Test"),
    Test(name: "Lactose Intolerance Test"),
    Test(name: "Helicobacter pylori Test"),
    Test(name: "Genetic Testing"),
    Test(name: "Allergy Testing"),
    Test(name: "Spirometry"),
    Test(name: "Skin Prick Test"),
    Test(name: "Mantoux Test"),
    Test(name: "Tuberculosis Test"),
    Test(name: "Fungal Culture Test"),
    Test(name: "Electrolyte Panel Test"),
    Test(name: "Celiac Disease Test"),
    Test(name: "Lyme Disease Test"),
    Test(name: "Syphilis Test"),
    Test(name: "Cholesterol Test"),
    Test(name: "Triglycerides Test"),
    Test(name: "Prothrombin Time (PT) Test"),
    Test(name: "Activated Partial Thromboplastin Time (APTT) Test"),
    Test(name: "D-Dimer Test"),
    Test(name: "Fibrinogen Test"),
    Test(name: "Brain Natriuretic Peptide (BNP) Test"),
    Test(name: "Troponin Test"),
    Test(name: "Hemoglobin Electrophoresis"),
    Test(name: "Gastric Emptying Study"),
    Test(name: "Hemoglobin Electrophoresis"),
    Test(name: "Gastric Emptying Study"),
    Test(name: "Colon Transit Study"),
    Test(name: "Magnetic Resonance Cholangiopancreatography (MRCP)"),
    Test(name: "Positron Emission Tomography (PET) Scan"),
    Test(name: "SPECT Scan"),
    Test(name: "Thallium Scan"),
    Test(name: "Perfusion Scan"),
    Test(name: "Barium Swallow Test"),
    Test(name: "Barium Meal Test"),
    Test(name: "Barium Enema"),
    Test(name: "Hysterosalpingogram"),
    Test(name: "Cystoscopy"),
    Test(name: "Laryngoscopy"),
    Test(name: "Rigid Bronchoscopy"),
    Test(name: "Flexible Bronchoscopy"),
    Test(name: "Electroretinography (ERG)"),
    Test(name: "Visual Evoked Potential (VEP) Test"),
    Test(name: "Auditory Brainstem Response (ABR) Test"),
    Test(name: "Electrooculography (EOG)"),
    Test(name: "Evoked Potential Tests"),
    Test(name: "Sleep Study (Polysomnography)"),
    Test(name: "Biochemical Tests"),
    Test(name: "Microbiological Tests"),
    Test(name: "Immunological Tests"),
    Test(name: "Histopathology Tests"),
    Test(name: "Cytopathology Tests"),
    Test(name: "Molecular Tests"),
    // Add more tests as needed
]
